name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 0 * * 0" # every Sunday at 00:00 UTC
  workflow_dispatch: # manual run option

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Users Table
        run: |
          curl -s "https://vdziplltitihyynjkxnb.supabase.co/rest/v1/users?select=id&limit=1" \
            -H "apikey: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}"
